# Utilise une image existante en tant que couche de base
FROM node:12-alpine

# Crée un répertoire de travail pour l'application
WORKDIR /app

# Copie le fichier package.json dans le répertoire de travail
COPY package*.json ./

# Installe les dépendances de l'application
RUN npm install

# Installe express
RUN npm install express

# Copie les fichiers de l'application dans le répertoire de travail
COPY . .

# Expose le port 80 pour accéder à l'application
EXPOSE 80

# Démarre l'application
CMD ["npm", "start"]
